// <auto-generated />
using System;
using Battleship.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace battleship.Migrations
{
    [DbContext(typeof(BattleshipContext))]
    partial class BattleshipContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "6.0.0-preview.2.21154.2")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Battleship.Models.Board", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GridString")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Boards");
                });

            modelBuilder.Entity("Battleship.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BoardAId")
                        .HasColumnType("int");

                    b.Property<int?>("BoardBId")
                        .HasColumnType("int");

                    b.Property<int>("GameStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BoardAId");

                    b.HasIndex("BoardBId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Battleship.Models.WarShip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BoardId")
                        .HasColumnType("int");

                    b.Property<int>("EndX")
                        .HasColumnType("int");

                    b.Property<int>("EndY")
                        .HasColumnType("int");

                    b.Property<int>("StartX")
                        .HasColumnType("int");

                    b.Property<int>("StartY")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.ToTable("Battleships");
                });

            modelBuilder.Entity("Battleship.Models.Game", b =>
                {
                    b.HasOne("Battleship.Models.Board", "BoardA")
                        .WithMany()
                        .HasForeignKey("BoardAId");

                    b.HasOne("Battleship.Models.Board", "BoardB")
                        .WithMany()
                        .HasForeignKey("BoardBId");

                    b.Navigation("BoardA");

                    b.Navigation("BoardB");
                });

            modelBuilder.Entity("Battleship.Models.WarShip", b =>
                {
                    b.HasOne("Battleship.Models.Board", null)
                        .WithMany("WarShips")
                        .HasForeignKey("BoardId");
                });

            modelBuilder.Entity("Battleship.Models.Board", b =>
                {
                    b.Navigation("WarShips");
                });
#pragma warning restore 612, 618
        }
    }
}
